[tool.poetry]
name = "app-name"
version = "0.1.0"
description = "Simple Python project template."
authors = ["mozkzki <mozkzki@gmail.com>"]
maintainers = ["mozkzki <mozkzki@gmail.com>"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/mozkzki/template-python-simple]"
repository = "https://github.com/mozkzki/template-python-simple]"
documentation = "https://github.com/mozkzki/template-python-simple]/wiki"
keywords = ['Python', 'template']
classifiers=[
    'Development Status :: 3 - Alpha',
    'License :: OSI Approved :: MIT License',
    'Intended Audience :: Developers',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
flake8 = "3.9.1"
mypy = "0.910"
pytest = "6.2.5"
black = "21.9b0"
pytest-cov = "2.12.1"
coverage = "5.5"
isort = "5.9.3"
Sphinx = "^4.2.0"
sphinx-rtd-theme = "^1.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
